### ISSUE TITLE
Install C++ compiler

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/vscode-python#21]
When installing python dependencies based on C++, I sometimes have troubles :

```python
pip install fasttext
```

>     RuntimeError: Unsupported compiler -- at least C++11 support is needed!

Installing g++ solves the problem ([here](https://github.com/facebookresearch/fastText/issues/924#issuecomment-539899833))

```shell
sudo apt-get install g++
```

Could we put that in `Dockerfile` such that it is available by default ?

**Comment by avouacr** [comment]
@linogaliana done, installing fasttext works fine now, thank's
