### ISSUE TITLE
Installing quarto on vscode ?

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/vscode-python#25]
Hi, 

I started to use [`quarto`](https://quarto.org/) which can be used with a nice VisualStudio extension (https://quarto.org/docs/tools/vscode.html). I think it is a great tool that would ease the use of Python with reproducible documents (alternative to Jupyter) and interaction computations. 

Would you consider adding `quarto` to the image as well as the extension ? I can do the PR, I have every pieces needed.

**Comment by olevitt** [comment]
Hi,

Sure, I recently heard of it and it looks really interesting. If you open a PR we will strongly consider merging it :)

Thanks !
